In [1]:
#Packages
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [5]:
#dataset

dataset = pd.read_csv('csgo_round_snapshots.csv')

X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values


array(['CT', 'CT', 'CT', ..., 'T', 'T', 'T'], dtype=object)

In [6]:
#enconding 

#Enconding categorical data
le = LabelEncoder()
X[:, 4] = le.fit_transform(X[:, 4])

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))




In [18]:
#y
y = le.fit_transform(y)
y


array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [19]:
#train, test split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [22]:
#Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [24]:
ann = tf.keras.models.Sequential()

In [28]:
ann.add(tf.keras.layers.Dense(units=10,activation='relu'))
ann.add(tf.keras.layers.Dense(units=10,activation='relu'))

In [29]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [30]:
ann.compile(optimizer= 'adam',loss='binary_crossentropy', metrics = ['accuracy'])

In [31]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
3061/3061 [==============================] - 2s 633us/step - loss: 0.4837 - accuracy: 0.7377
Epoch 2/100
3061/3061 [==============================] - 2s 632us/step - loss: 0.4545 - accuracy: 0.7530
Epoch 3/100
3061/3061 [==============================] - 2s 637us/step - loss: 0.4487 - accuracy: 0.7563
Epoch 4/100
3061/3061 [==============================] - 2s 620us/step - loss: 0.4456 - accuracy: 0.7578
Epoch 5/100
3061/3061 [==============================] - 2s 643us/step - loss: 0.4432 - accuracy: 0.7592
Epoch 6/100
3061/3061 [==============================] - 2s 634us/step - loss: 0.4413 - accuracy: 0.7596
Epoch 7/100
3061/3061 [==============================] - 2s 626us/step - loss: 0.4398 - accuracy: 0.7607
Epoch 8/100
3061/3061 [==============================] - 2s 669us/step - loss: 0.4392 - accuracy: 0.7601
Epoch 9/100
3061/3061 [==============================] - 2s 638us/step - loss: 0.4381 - accuracy: 0.7622
Epoch 10/100
3061/3061 [==============================]

In [32]:
#putting the prediction and real together
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 1]
 ...
 [1 0]
 [0 0]
 [0 1]]


In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[9648 2297]
 [3551 8986]]


0.7611306265827955